ecommerce_accueil_accueil:
    path:     /
    defaults: { _controller: ecommerceAccueilBundle:Accueil:index }

ecommerce_accueil_apropos:
    path:     /apropos
    defaults: { _controller: ecommerceAccueilBundle:Accueil:apropos }

ecommerce_accueil_contact:
    path:     /contact
    defaults: { _controller: ecommerceAccueilBundle:Accueil:contact }

ecommerce_accueil_error404:
    path:     /url-not-found
    defaults: { _controller: ecommerceAccueilBundle:Accueil:error404 }