ecommerce_user_homepage:
    path:     /index
    defaults: { _controller: ecommerceUserBundle:User:index }

ecommerce_user_profile:
    path:     /profile
    defaults: { _controller: ecommerceUserBundle:Profile:show }

ecommerce_user_edit_profile:
    path:     /edit
    defaults: { _controller: ecommerceUserBundle:Profile:edit }