services:
  redirect.after.login:
    class: ecommerce\UserBundle\Redirection\AfterLoginRedirection
    arguments: [@router]

#    ecommerce_user.example:
#        class: ecommerce\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]