<?php

namespace ecommerce\ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getProductComments($article)
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('c')
            ->where('c.article = :article')
            ->setParameter('article', $article)
            ->leftJoin('c.author', 'aut')
            ->addSelect('aut')
            ->orderBy('c.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}