<?php

namespace ecommerce\ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    public function getUserReviews($user)
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('r')
            ->where('r.user = :user')
            ->setParameter('user', $user)
            ->leftJoin('r.user', 'u')
            ->addSelect('u')
            ->leftJoin('r.author', 'aut')
            ->addSelect('aut')
            ->orderBy('r.date', 'DESC')
            ->setMaxResults(3)
            ->getQuery();

        return $query->getResult();
    }
}
