ecommerce_article_categorie:
    path:     /cat/{id}
    defaults: { _controller: ecommerceArticleBundle:Article:genre }
    requirements:
        id:  \d+

ecommerce_article_detail:
    path:     /itm/{id}
    defaults: { _controller: ecommerceArticleBundle:Article:detail }
    requirements:
        id:  \d+

ecommerce_article_create:
    path:     /create
    defaults: { _controller: ecommerceArticleBundle:Article:create }