ecommerce_article_categorie:
    path:     /c/{id}/{numberItemsPerPage}/{page}
    defaults: { _controller: ecommerceArticleBundle:Article:genre, numberItemsPerPage: 12, page: 1 }
    requirements:
        id:  \d+
        numberItemsPerPage:  \d+
        page:  \d+

ecommerce_article_detail:
    path:     /itm/{id}/{slug}
    defaults: { _controller: ecommerceArticleBundle:Article:detail }
    requirements:
        id:  \d+

ecommerce_article_create:
    path:     /create
    defaults: { _controller: ecommerceArticleBundle:Article:create }

ecommerce_article_publications:
    path:     /publications/{page}/{numberItemsPerPage}
    defaults: { _controller: ecommerceArticleBundle:Article:publications, page: 1, numberItemsPerPage: 10 }
    requirements:
            page:  \d+
            numberItemsPerPage:  \d+

ecommerce_article_publisher_items:
    path:     /u/{id}/{username}/{numberItemsPerPage}/{page}
    defaults: { _controller: ecommerceArticleBundle:Article:publisherItems, numberItemsPerPage: 12, page: 1 }
    requirements:
        id:  \d+
        numberItemsPerPage:  \d+
        page:  \d+

ecommerce_article_delete:
    path:     /delete/{id}
    defaults: { _controller: ecommerceArticleBundle:Article:delete }
    requirements:
        id:  \d+

ecommerce_article_edit:
    path:     /edit/{id}
    defaults: { _controller: ecommerceArticleBundle:Article:edit }
    requirements:
        id:  \d+

ecommerce_article_search:
    path:     /s/{numberItemsPerPage}/{page}/{item}
    defaults: { _controller: ecommerceArticleBundle:Article:search, numberItemsPerPage: 12, page: 1, item: null }
    requirements:
            numberItemsPerPage:  \d+
            page:  \d+
            item: \w+