ecommerce_article_categorie:
    path:     /cat/{id}/{number}/{page}
    defaults: { _controller: ecommerceArticleBundle:Article:genre, number: 12, page: 1 }
    requirements:
        id:  \d+
        number:  \d+
        page:  \d+

ecommerce_article_detail:
    path:     /itm/{id}/{slug}
    defaults: { _controller: ecommerceArticleBundle:Article:detail }
    requirements:
        id:  \d+

ecommerce_article_create:
    path:     /create
    defaults: { _controller: ecommerceArticleBundle:Article:create }